baseURL = "https://sweetytalks.xyz/"
languageCode = "en-us"
title = "SweetyTalks"
theme = "mainroad"
paginate = 5

[Params]
  subtitle = "Sweety ❤️ Bava Forever"
  description = "A sweet adda of long-distance love, trading, and movies."
  author = "Cherry Bava"
  dateformat = "02 Jan 2006"

[Params.logo]
  subtitle = "Let's share our heartbeats, one article at a time 💖"

# Tell Hugo to put the generated site into /docs so GitHub Pages can serve it
# publishDir = "docs"
